# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
# 1,2,3,5,8,13,21,34,55,89
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

# MAX = 100
MAX = 4_000_000
sum = 0
RecentFibNums = (2, 1)
while RecentFibNums[0] < MAX:
    if RecentFibNums[0] % 2 == 0:
        sum += RecentFibNums[0]
    RecentFibNums = (RecentFibNums[0]+ RecentFibNums[1], RecentFibNums[0] )

print("The answer is: ", sum)